### ISSUE TITLE
Uncaught Exception Error loading jupyterlab-sql

### ISSUE THREAD

**Issue by patrick-ryan1** [pbugnion/jupyterlab-sql#130]
I am seeing a repeated issue where, after installing jupyterlab-sql, I am seeing the following error when launching "jupyter lab".  Additionally, the Extensions panel is showing an "Error: 500 (Internal Server Error)" and no extensions appear.  

Completely removing is only option to get remove erros seen on console and allow extensions to load. 

* Pip  uninstall jupyterlab_sql
* jupyter serverextensions disable jupyterlab_sql
* jupyter lab build

I am using Annaconda and Conda  to build virtual environment.  I have tested with  Jupyterlab 1.2.7, 1.2.6 and 1.2.3 and see the same issue across each

Environment script

conda create --name Jupyter python=3.7
conda activate Jupyter
conda install requests pandas matplotlib seaborn curl scipy numpy nodejs black ipywidgets black 
jupyterlab==1.2.3 voila
pip install nbdime
pip install jupyterlab_sql
jupyter labextension install  @jupyter-widgets/jupyterlab-manager 
jupyter labextension install  jupyter-matplotlib  jupyterlab-datawidgets @jupyterlab/git
jupyter serverextension enable jupyterlab_sql --py --sys-prefix
jupyter lab build 

Here is console output when loading the jupyterlab_sql serverextension

`[E 16:38:34.497 LabApp] 500 GET /lab/api/extensions?1583624306357 (::1) 6057.91ms referer=http://localhost:8888/lab/workspaces/auto-u?clone
[E 16:38:34.499 LabApp] Uncaught exception GET /lab/api/extensions?1583624306424 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/lab/api/extensions?1583624306424', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\tornado\web.py", line 1699, in _execute
        result = await result
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\tornado\web.py", line 1699, in _execute
        result = await result
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\jupyterlab\handlers\extension_manager_handler.py", line 222, in get
        extensions = yield self.manager.list_extensions()
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\jupyterlab\handlers\extension_manager_handler.py", line 222, in get
        extensions = yield self.manager.list_extensions()
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\jupyterlab\handlers\extension_manager_handler.py", line 92, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\jupyterlab\handlers\extension_manager_handler.py", line 92, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\jupyterlab\handlers\extension_manager_handler.py", line 161, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\jupyterlab\handlers\extension_manager_handler.py", line 161, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\jupyterlab\handlers\extension_manager_handler.py", line 195, in _load_outdated
        app_options=self.app_options
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\concurrent\futures\_base.py", line 428, in result
        return self.__get_result()
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\concurrent\futures\_base.py", line 384, in __get_result
        raise self._exception
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\jupyterlab\commands.py", line 550, in get_latest_compatible_package_versions
        return handler.latest_compatible_package_versions(names)
      File "C:\Users\usparya\AppData\Local\Continuum\anaconda3\envs\jupyter_sql\lib\site-packages\jupyterlab\commands.py", line 1652, in latest_compatible_package_versions
        for version, data in sorted(versions.items(),
    AttributeError: 'list' object has no attribute 'items'
[W 16:38:34.503 LabApp] Unhandled error`

**Comment by jseabold** [comment]
Duplicated by #131.
