### ISSUE TITLE
"jupyterlab-sql" is outdated，jupyterlab-sql-0.3.3,JupyterLab 3.0.6

### ISSUE THREAD

**Issue by shasky2014** [pbugnion/jupyterlab-sql#147]
```
Successfully installed jupyterlab-sql-0.3.3

PS C:\Users\neon> jupyter serverextension enable jupyterlab_sql --py --sys-prefix 
Enabling: jupyterlab_sql
- Writing config: c:\users\neon\appdata\local\programs\python\python39\etc\jupyter
    - Validating...
      jupyterlab_sql  ok

PS C:\Users\neon> jupyter lab build
[LabBuildApp] JupyterLab 3.0.6
[LabBuildApp] Building in c:\users\neon\appdata\local\programs\python\python39\share\jupyter\lab
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] WARNING | The extension "jupyterlab-sql" is outdated.
```
这版本都是最新的了吧？

`jupyterlab-sql-0.3.3`
`JupyterLab 3.0.6`

还没发卸载 jupyterlab-sql ?

装不上不用他了行吧，怎么卸载或者弃用？

**Comment by shasky2014** [comment]
```
[LabBuildApp] Building in c:\users\neon\appdata\local\programs\python\python39\share\jupyter\lab
[LabBuildApp] Node v15.7.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] > node c:\users\neon\appdata\local\programs\python\python39\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
warning ..\..\..\..\..\..\..\..\..\package.json: No license field
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.57s.

[LabBuildApp] > node c:\users\neon\appdata\local\programs\python\python39\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.21.1
warning ..\..\..\..\..\..\..\..\..\package.json: No license field
$ c:\users\neon\appdata\local\programs\python\python39\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer --fail
Done in 0.43s.

[LabBuildApp] > node c:\users\neon\appdata\local\programs\python\python39\lib\site-packages\jupyterlab\staging\yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.21.1
warning ..\..\..\..\..\..\..\..\..\package.json: No license field
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] [31mTypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (c:\users\neon\appdata\local\programs\python\python39\share\jupyter\lab\staging\node_modules\webpack\lib\javascript\JavascriptModulesPlugin.js:119:10)
    at c:\users\neon\appdata\local\programs\python\python39\share\jupyter\lab\staging\node_modules\terser-webpack-plugin\dist\index.js:566:67
    at _next36 (eval at create (c:\Users\neon\AppData\Local\Programs\Python\Python39\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:40:1)
    at _next14 (eval at create (c:\Users\neon\AppData\Local\Programs\Python\Python39\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:97:1)
    at Hook.eval [as call] (eval at create (c:\Users\neon\AppData\Local\Programs\Python\Python39\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:129:1)
    at Hook.CALL_DELEGATE [as _call] (c:\Users\neon\AppData\Local\Programs\Python\Python39\share\jupyter\lab\staging\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (c:\Users\neon\AppData\Local\Programs\Python\Python39\share\jupyter\lab\staging\node_modules\webpack\lib\Compiler.js:993:26)
    at c:\Users\neon\AppData\Local\Programs\Python\Python39\share\jupyter\lab\staging\node_modules\webpack\lib\Compiler.js:1035:29
    at Hook.eval [as callAsync] (eval at create (c:\Users\neon\AppData\Local\Programs\Python\Python39\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (c:\Users\neon\AppData\Local\Programs\Python\Python39\share\jupyter\lab\staging\node_modules\tapable\lib\Hook.js:18:14)[39m
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "c:\users\neon\appdata\local\programs\python\python39\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "c:\users\neon\appdata\local\programs\python\python39\lib\site-packages\jupyterlab\labapp.py", line 168, in start
    raise e

[LabBuildApp]   File "c:\users\neon\appdata\local\programs\python\python39\lib\site-packages\jupyterlab\labapp.py", line 164, in start
    build(name=self.name, version=self.version,

[LabBuildApp]   File "c:\users\neon\appdata\local\programs\python\python39\lib\site-packages\jupyterlab\commands.py", line 463, in build
    return handler.build(name=name, version=version, static_url=static_url,

[LabBuildApp]   File "c:\users\neon\appdata\local\programs\python\python39\lib\site-packages\jupyterlab\commands.py", line 675, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab

```

**Comment by hackeye** [comment]
JupyterLab v3.0.7
Other labextensions (built into JupyterLab)
   app dir: /opt/homebrew/anaconda3/share/jupyter/lab
        @jupyterlab/debugger v3.0.5 enabled OK
        @jupyterlab/geojson-extension v3.0.0 enabled OK
        @jupyterlab/server-proxy v2.1.2 enabled OK
        jupyter-matplotlib v0.8.3 enabled OK
        jupyterlab-code-snippets v2.0.1 enabled OK
        jupyterlab-sql v0.3.3 enabled  X

   The following extension are outdated:
        jupyterlab-sql

   Consider running "jupyter labextension update --all" to check for updates.

**Comment by mithunjmistry** [comment]
Any update on it?

**Comment by MaximoTrinidad** [comment]
@mithunjmistry 
I have the same situation:
```
warning during build: The extension "jupyterlab-sql" is outdated.
```

Ran the cmd: "jupyter labextension update --all``
and got: 
```
(base) PS C:\Users\max_t> jupyter labextension update --all
No compatible version found for jupyterlab-sql!
```
:(

**Comment by r-nishant** [comment]
Will downgrading jupyterlab to an earlier version be helpful for using this extension? 

If yes, then will it effect the support for xeus kernal and R studio.

**Comment by rachel2149** [comment]
what's the latest jupyterlab version that's compatible with jupyterlab-sql? thx!

**Comment by YaoFANGUK** [comment]
> ```
> Successfully installed jupyterlab-sql-0.3.3
> 
> PS C:\Users\neon> jupyter serverextension enable jupyterlab_sql --py --sys-prefix 
> Enabling: jupyterlab_sql
> - Writing config: c:\users\neon\appdata\local\programs\python\python39\etc\jupyter
>     - Validating...
>       jupyterlab_sql  ok
> 
> PS C:\Users\neon> jupyter lab build
> [LabBuildApp] JupyterLab 3.0.6
> [LabBuildApp] Building in c:\users\neon\appdata\local\programs\python\python39\share\jupyter\lab
> [LabBuildApp] Building jupyterlab assets (production, minimized)
> [LabBuildApp] WARNING | The extension "jupyterlab-sql" is outdated.
> ```
> 
> 这版本都是最新的了吧？
> 
> `jupyterlab-sql-0.3.3` `JupyterLab 3.0.6`
> 
> 还没发卸载 jupyterlab-sql ?
> 
> 装不上不用他了行吧，怎么卸载或者弃用？

```shell
jupyter labextension uninstall jupyterlab-sql
```

```shell
jupyter lab build
```

**Comment by skaag** [comment]
I'm experiencing the exact same thing in my environment. I followed the install instructions, and the extension shows up in the list of server extensions, but nothing shows up in the GUI.

I'm including some information about my environment.

**Python version:**

```
$ python3 --version
Python 3.8.10
```

**Lab Extensions List:**

```
$ jupyter labextension list

JupyterLab v3.1.19
/usr/local/share/jupyter/labextensions
        nbdime-jupyterlab v2.1.1 enabled OK
        @jupyterlab/git v0.34.2 enabled OK (python, jupyterlab-git)
        @voila-dashboards/jupyterlab-preview v2.1.1 enabled OK (python, voila)

Other labextensions (built into JupyterLab)
   app dir: /home/labs/.local/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK
        @tiburon-security/jupyterlab_scheduler v0.1.5 enabled OK
        jupyterlab-chart-editor v4.14.3 enabled OK
        jupyterlab-dash v0.4.0 enabled OK
        jupyterlab-drawio v0.9.0 enabled OK
        jupyterlab_scheduler v0.1.3 enabled OK
```

**Server extension list:**

```
$ jupyter serverextension list
config dir: /home/labs/.local/etc/jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 3.1.19 OK
    jupyterlab_scheduler  enabled
    - Validating...
      jupyterlab_scheduler  OK
config dir: /usr/etc/jupyter
    jupyterlab_sql  enabled
    - Validating...
      jupyterlab_sql  OK
config dir: /usr/local/etc/jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 3.1.19 OK
    jupyterlab_git  enabled
    - Validating...
      jupyterlab_git 0.34.2 OK
    nbdime  enabled
    - Validating...
      nbdime 3.1.1 OK
    voila.server_extension  enabled
    - Validating...
      voila.server_extension  OK
```

**OS information:**

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

**Output of `jupyter lab build`:**

```
$ jupyter lab build
[LabBuildApp] JupyterLab 3.1.19
[LabBuildApp] Building in /home/labs/.local/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (production, minimized)
```

Please help! I need to dynamically load datasets from PostgreSQL. Thank you :-D
